# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct-1M
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: none
dataset_configs:
- all
preprocessing_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
eval_on_start: true
eval_strategy: steps
eval_steps: 8
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-7B-1M-SFT-LongStory
hub_strategy: every_save
learning_rate: 2.0e-5
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 17000
use_liger: false
max_steps: -1
num_train_epochs: 10
output_dir: output_sft_7b
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
wandb_entity: WANDB_ENTITY
wandb_project: WANDB_PROJECT
load_best_model_at_end: true
metric_for_best_model: loss
save_strategy: steps
save_total_limit: 1
save_steps: 8
seed: 42
warmup_ratio: 0.1